services:
  db:
    image: postgres:15-alpine
    container_name: iams_db
    restart: always
    environment:
      POSTGRES_USER: ubd_user
      POSTGRES_PASSWORD: ubd_password
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432" # Acces extern pentru instrumente GUI (DBeaver)
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d 

  backend:
    build: .
    container_name: iams_backend
    ports:
      - "5000:5000" # Acces la aplicatia web
    environment:
      # String de conectare la baza de date (foloseste numele serviciului 'db')
      DATABASE_URL: postgresql://ubd_user:ubd_password@db:5432/inventory_db

    depends_on:
      - db

volumes:
  pgdata:
